[package]
name = "todotool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = {version = "0.4", features = ["image"]}
chrono = "0.4"
iced_core = "0.10.0"
iced_style = "0.9.0"
image = "0.24.6"
